Description: Master node stack for a k3s cluster. Exports SG and master IPs.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
    Description: Name of an existing EC2 KeyPair to enable SSH access
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0bbdd8c17ed981ef9
    Description: Ubuntu Server 22.04 LTS AMI
  InstanceType:
    Type: String
    Default: t2.medium
    Description: EC2 instance type for the node
  ScriptUrl:
    Type: String
    Default: https://raw.githubusercontent.com/rominjun/devsecops/main/k3s-install.sh
    Description: URL to fetch k3s-install.sh from

Resources:
  k3sSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and k3s control plane access
      VpcId: !ImportValue k3s-vpc:VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 10250
          ToPort: 10250
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 30000
          ToPort: 32767
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - LabRole

  MasterNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      SubnetId: !ImportValue k3s-vpc:PublicSubnet
      SecurityGroupIds:
        - !Ref k3sSecurityGroup
      IamInstanceProfile: !Ref NodeInstanceProfile
      Tags:
        - Key: Name
          Value: k3s-master
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          # Ensure hostname is set before k3s install
          hostnamectl set-hostname cn1

          apt-get update -y
          apt-get install -y curl awscli
          curl -o /usr/local/bin/k3s.sh ${ScriptUrl}
          chmod +x /usr/local/bin/k3s.sh
          /usr/local/bin/k3s.sh server
          TOKEN=$(cat /var/lib/rancher/k3s/server/node-token)
          aws ssm put-parameter --region ${AWS::Region} --name /k3s/token --type SecureString --value "$TOKEN" --overwrite

Outputs:
  SecurityGroupId:
    Description: Security group used by k3s nodes
    Value: !Ref k3sSecurityGroup
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SecurityGroupId ] ]
  MasterPrivateIP:
    Description: Private IP address of the master node
    Value: !GetAtt MasterNode.PrivateIp
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MasterPrivateIP ] ]
  MasterPublicIP:
    Description: Public IP address of the master node
    Value: !GetAtt MasterNode.PublicIp
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MasterPublicIP ] ]

