name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            hhmbroekman/student-app:latest

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run container and smoke test
        run: |
          docker run -d --name student-app -p 80:5000 hhmbroekman/student-app:latest
          # give it a moment to start
          sleep 10
          curl -fsS http://localhost/ || (docker logs student-app; exit 1)
          docker stop student-app >/dev/null 2>&1 || true
          docker rm student-app >/dev/null 2>&1 || true

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: |
          sudo kubectl delete deployment --all || true
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/deployment.yaml --force
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/nginx-service.yaml --force

